version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: skylark
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: skylark-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/skylark
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
  worker:
    build: ./worker
    container_name: worker
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data: